kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "cd /home/runner/workspace/artifacts/hr-backend && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"

[services.production]

[services.production.build]
args = ["pip", "install", "-r", "artifacts/hr-backend/requirements.txt"]

[services.production.run]
args = ["sh", "-c", "cd artifacts/hr-backend && uvicorn main:app --host 0.0.0.0 --port 8080"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
